import { SvelteComponentTyped } from 'svelte';
declare const __propDef: {
	props: {
		[x: string]: any;
		/** Required. Set a unique name for the input.*/
		name: string;
		/** Provide a unique input id. Auto-generated by default*/
		id?: string | undefined;
		/** Set the input value.*/
		value?: number | undefined;
		/** Set the input minimum range.*/
		min?: number | undefined;
		/** Set the input maximum range.*/
		max?: number | undefined;
		/** Set the input step offset.*/
		step?: number | undefined;
		/** Enables tick marks. See browser support below.*/
		ticked?: boolean | undefined;
		/** Provide classes to set the input accent color.*/
		accent?: string | undefined;
		/** A semantic ARIA label.*/
		label?: string | undefined;
	};
	events: {
		click: MouseEvent;
		change: Event;
		blur: FocusEvent;
	} & {
		[evt: string]: CustomEvent<any>;
	};
	slots: {
		default: {};
		trail: {};
	};
};
export type RangeSliderProps = typeof __propDef.props;
export type RangeSliderEvents = typeof __propDef.events;
export type RangeSliderSlots = typeof __propDef.slots;
export default class RangeSlider extends SvelteComponentTyped<RangeSliderProps, RangeSliderEvents, RangeSliderSlots> {}
export {};
