---
name: Build Frontend

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "web/app/**.json"
      - "web/app/**.cjs"
      - "web/app/**.ts"
      - "web/app/**.js"
      - "web/app/**.svelte"
  pull_request:
    branches: [main]
    paths:
      - "web/app/**.json"
      - "web/app/**.cjs"
      - "web/app/**.ts"
      - "web/app/**.js"
      - "web/app/**.svelte"
  schedule:
    - cron: "0 10 * * 1"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Build Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: "web/app/package-lock.json"

      - name: Install NPM dependencies
        run: npm ci && git diff --exit-code
        working-directory: web/app

      - name: make lint-fe
        run: make lint-fe

      - name: make build-fe
        run: make build-fe

      - name: make test-fe
        run: make test-fe
